### ISSUE TITLE
[ERROR] Check variable font instances have correct coordinate values

### ISSUE THREAD

**Issue by kosbarts** [kosbarts/Commissioner#10]
* 💔 **ERROR** Failed with KeyError: 'slnt'

No more info.

**Comment by kosbarts** [comment]
@davelab this seems to be some error I cannot understand. Any ideas?

**Comment by kosbarts** [comment]
Issue has been discussed here: (https://github.com/googlefonts/fontbakery/issues/2701)

**Comment by kosbarts** [comment]
Reported and waiting.

**Comment by davelab6** [comment]
https://github.com/googlefonts/fontbakery/issues/2701 is closed, please update your fontbakery and confirm if this still errors/fails :)
