### ISSUE TITLE
[FAIL] Check variable font instances have correct names

### ISSUE THREAD

**Issue by kosbarts** [kosbarts/Commissioner#12]
<summary>🔥 <b>FAIL:</b> Check variable font instances have correct names</summary>

* [com.google.fonts/check/varfont_instance_names](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/varfont_instance_names)

* 🔥 **FAIL** Instance name "Flair Thin" is incorrect. It should be "Thin" [code: bad-name]
* 🔥 **FAIL** Instance name "Flair ExtraLight" is incorrect. It should be "ExtraLight" [code: bad-name]
* 🔥 **FAIL** Instance name "Flair Light" is incorrect. It should be "Light" [code: bad-name]
* 🔥 **FAIL** Instance name "Flair Regular" is incorrect. It should be "Regular" [code: bad-name]
* 🔥 **FAIL** Instance name "Flair Medium" is incorrect. It should be "Medium" [code: bad-name]
* 🔥 **FAIL** Instance name "Flair SemiBold" is incorrect. It should be "SemiBold" [code: bad-name]
* 🔥 **FAIL** Instance name "Flair Bold" is incorrect. It should be "Bold" [code: bad-name]
* 🔥 **FAIL** Instance name "Flair ExtraBold" is incorrect. It should be "ExtraBold" [code: bad-name]
* 🔥 **FAIL** Instance name "Flair Black" is incorrect. It should be "Black" [code: bad-name]
* 🔥 **FAIL** Instance name "Flair Thin Italic" is incorrect. It should be "Thin Italic" [code: bad-name]
* 🔥 **FAIL** Instance name "Flair ExtraLight Italic" is incorrect. It should be "ExtraLight Italic" [code: bad-name]
* 🔥 **FAIL** Instance name "Flair Light Italic" is incorrect. It should be "Light Italic" [code: bad-name]
* 🔥 **FAIL** Instance name "Flair Italic" is incorrect. It should be "Italic" [code: bad-name]
* 🔥 **FAIL** Instance name "Flair Medium Italic" is incorrect. It should be "Medium Italic" [code: bad-name]
* 🔥 **FAIL** Instance name "Flair SemiBold Italic" is incorrect. It should be "SemiBold Italic" [code: bad-name]
* 🔥 **FAIL** Instance name "Flair Bold Italic" is incorrect. It should be "Bold Italic" [code: bad-name]
* 🔥 **FAIL** Instance name "Flair ExtraBold Italic" is incorrect. It should be "ExtraBold Italic" [code: bad-name]
* 🔥 **FAIL** Instance name "Flair Black Italic" is incorrect. It should be "Black Italic" [code: bad-name]
* 🔥 **FAIL** Instance name "Loud Thin" is incorrect. It should be "Thin" [code: bad-name]
* 🔥 **FAIL** Instance name "Loud ExtraLight" is incorrect. It should be "ExtraLight" [code: bad-name]
* 🔥 **FAIL** Instance name "Loud Light" is incorrect. It should be "Light" [code: bad-name]
* 🔥 **FAIL** Instance name "Loud Regular" is incorrect. It should be "Regular" [code: bad-name]
* 🔥 **FAIL** Instance name "Loud Medium" is incorrect. It should be "Medium" [code: bad-name]
* 🔥 **FAIL** Instance name "Loud SemiBold" is incorrect. It should be "SemiBold" [code: bad-name]
* 🔥 **FAIL** Instance name "Loud Bold" is incorrect. It should be "Bold" [code: bad-name]
* 🔥 **FAIL** Instance name "Loud ExtraBold" is incorrect. It should be "ExtraBold" [code: bad-name]
* 🔥 **FAIL** Instance name "Loud Black" is incorrect. It should be "Black" [code: bad-name]
* 🔥 **FAIL** Instance name "Loud Thin Italic" is incorrect. It should be "Thin Italic" [code: bad-name]
* 🔥 **FAIL** Instance name "Loud ExtraLight Italic" is incorrect. It should be "ExtraLight Italic" [code: bad-name]
* 🔥 **FAIL** Instance name "Loud Light Italic" is incorrect. It should be "Light Italic" [code: bad-name]
* 🔥 **FAIL** Instance name "Loud Italic" is incorrect. It should be "Italic" [code: bad-name]
* 🔥 **FAIL** Instance name "Loud Medium Italic" is incorrect. It should be "Medium Italic" [code: bad-name]
* 🔥 **FAIL** Instance name "Loud SemiBold Italic" is incorrect. It should be "SemiBold Italic" [code: bad-name]
* 🔥 **FAIL** Instance name "Loud Bold Italic" is incorrect. It should be "Bold Italic" [code: bad-name]
* 🔥 **FAIL** Instance name "Loud ExtraBold Italic" is incorrect. It should be "ExtraBold Italic" [code: bad-name]
* 🔥 **FAIL** Instance name "Loud Black Italic" is incorrect. It should be "Black Italic" [code: bad-name]
* 🔥 **FAIL** This will cause problems with some of the Google Fonts systems that look up fonts by their style names. This must be fixed! [code: bad-instance-names]

**Comment by kosbarts** [comment]
This one does not seem to make much sense. How will so many different variable instances be differentiated if the naming is limited to the very basic "thin to black (plus italics)" scheme?

**Comment by kosbarts** [comment]
@davelab6 how are the instances of an extended variable font supposed to be named? It seems that fontbakery expects every Thin to be called just Thin. Is there a document that specifies what you expect from families that have multiple versions of weights?

**Comment by davelab6** [comment]
This check is FUBAR :) 

@felipesanches this is an urgent issue. The weight parts of these styles names are all correct, so this check should pass.

**Comment by m4rc1e** [comment]
This is fixed.

New results.

```
 >> com.google.fonts/check/varfont_instance_names
    Check variable font instances have correct names
    with /Users/marcfoley/Type/upstream_families/Commissioner/fonts/variable/Commissioner[FLAR,VOLM,slnt,wght].ttf

    * WARN: Instance "Flair Thin": contains the following unparsable tokens "['Flair']"
    * WARN: Instance "Flair Thin": cannot determine instance name due to unparsable tokens
    * WARN: Instance "Flair ExtraLight": contains the following unparsable tokens "['Flair']"
    * WARN: Instance "Flair ExtraLight": cannot determine instance name due to unparsable tokens
    * WARN: Instance "Flair Light": contains the following unparsable tokens "['Flair']"
    * WARN: Instance "Flair Light": cannot determine instance name due to unparsable tokens
    * WARN: Instance "Flair Regular": contains the following unparsable tokens "['Flair']"
    * WARN: Instance "Flair Regular": cannot determine instance name due to unparsable tokens
    * WARN: Instance "Flair Medium": contains the following unparsable tokens "['Flair']"
    * WARN: Instance "Flair Medium": cannot determine instance name due to unparsable tokens
    * WARN: Instance "Flair SemiBold": contains the following unparsable tokens "['Flair']"
    * WARN: Instance "Flair SemiBold": cannot determine instance name due to unparsable tokens
    * WARN: Instance "Flair Bold": contains the following unparsable tokens "['Flair']"
    * WARN: Instance "Flair Bold": cannot determine instance name due to unparsable tokens
    * WARN: Instance "Flair ExtraBold": contains the following unparsable tokens "['Flair']"
    * WARN: Instance "Flair ExtraBold": cannot determine instance name due to unparsable tokens
    * WARN: Instance "Flair Black": contains the following unparsable tokens "['Flair']"
    * WARN: Instance "Flair Black": cannot determine instance name due to unparsable tokens
    * WARN: Instance "Flair Thin Italic": contains the following unparsable tokens "['Flair']"
    * WARN: Instance "Flair Thin Italic": cannot determine instance name due to unparsable tokens
    * WARN: Instance "Flair ExtraLight Italic": contains the following unparsable tokens "['Flair']"
    * WARN: Instance "Flair ExtraLight Italic": cannot determine instance name due to unparsable tokens
    * WARN: Instance "Flair Light Italic": contains the following unparsable tokens "['Flair']"
    * WARN: Instance "Flair Light Italic": cannot determine instance name due to unparsable tokens
    * WARN: Instance "Flair Italic": contains the following unparsable tokens "['Flair']"
    * WARN: Instance "Flair Italic": cannot determine instance name due to unparsable tokens
    * WARN: Instance "Flair Medium Italic": contains the following unparsable tokens "['Flair']"
    * WARN: Instance "Flair Medium Italic": cannot determine instance name due to unparsable tokens
    * WARN: Instance "Flair SemiBold Italic": contains the following unparsable tokens "['Flair']"
    * WARN: Instance "Flair SemiBold Italic": cannot determine instance name due to unparsable tokens
    * WARN: Instance "Flair Bold Italic": contains the following unparsable tokens "['Flair']"
    * WARN: Instance "Flair Bold Italic": cannot determine instance name due to unparsable tokens
    * WARN: Instance "Flair ExtraBold Italic": contains the following unparsable tokens "['Flair']"
    * WARN: Instance "Flair ExtraBold Italic": cannot determine instance name due to unparsable tokens
    * WARN: Instance "Flair Black Italic": contains the following unparsable tokens "['Flair']"
    * WARN: Instance "Flair Black Italic": cannot determine instance name due to unparsable tokens
    * WARN: Instance "Loud Thin": contains the following unparsable tokens "['Loud']"
    * WARN: Instance "Loud Thin": cannot determine instance name due to unparsable tokens
    * WARN: Instance "Loud ExtraLight": contains the following unparsable tokens "['Loud']"
    * WARN: Instance "Loud ExtraLight": cannot determine instance name due to unparsable tokens
    * WARN: Instance "Loud Light": contains the following unparsable tokens "['Loud']"
    * WARN: Instance "Loud Light": cannot determine instance name due to unparsable tokens
    * WARN: Instance "Loud Regular": contains the following unparsable tokens "['Loud']"
    * WARN: Instance "Loud Regular": cannot determine instance name due to unparsable tokens
    * WARN: Instance "Loud Medium": contains the following unparsable tokens "['Loud']"
    * WARN: Instance "Loud Medium": cannot determine instance name due to unparsable tokens
    * WARN: Instance "Loud SemiBold": contains the following unparsable tokens "['Loud']"
    * WARN: Instance "Loud SemiBold": cannot determine instance name due to unparsable tokens
    * WARN: Instance "Loud Bold": contains the following unparsable tokens "['Loud']"
    * WARN: Instance "Loud Bold": cannot determine instance name due to unparsable tokens
    * WARN: Instance "Loud ExtraBold": contains the following unparsable tokens "['Loud']"
    * WARN: Instance "Loud ExtraBold": cannot determine instance name due to unparsable tokens
    * WARN: Instance "Loud Black": contains the following unparsable tokens "['Loud']"
    * WARN: Instance "Loud Black": cannot determine instance name due to unparsable tokens
    * WARN: Instance "Loud Thin Italic": contains the following unparsable tokens "['Loud']"
    * WARN: Instance "Loud Thin Italic": cannot determine instance name due to unparsable tokens
    * WARN: Instance "Loud ExtraLight Italic": contains the following unparsable tokens "['Loud']"
    * WARN: Instance "Loud ExtraLight Italic": cannot determine instance name due to unparsable tokens
    * WARN: Instance "Loud Light Italic": contains the following unparsable tokens "['Loud']"
    * WARN: Instance "Loud Light Italic": cannot determine instance name due to unparsable tokens
    * WARN: Instance "Loud Italic": contains the following unparsable tokens "['Loud']"
    * WARN: Instance "Loud Italic": cannot determine instance name due to unparsable tokens
    * WARN: Instance "Loud Medium Italic": contains the following unparsable tokens "['Loud']"
    * WARN: Instance "Loud Medium Italic": cannot determine instance name due to unparsable tokens
    * WARN: Instance "Loud SemiBold Italic": contains the following unparsable tokens "['Loud']"
    * WARN: Instance "Loud SemiBold Italic": cannot determine instance name due to unparsable tokens
    * WARN: Instance "Loud Bold Italic": contains the following unparsable tokens "['Loud']"
    * WARN: Instance "Loud Bold Italic": cannot determine instance name due to unparsable tokens
    * WARN: Instance "Loud ExtraBold Italic": contains the following unparsable tokens "['Loud']"
    * WARN: Instance "Loud ExtraBold Italic": cannot determine instance name due to unparsable tokens
    * WARN: Instance "Loud Black Italic": contains the following unparsable tokens "['Loud']"
    * WARN: Instance "Loud Black Italic": cannot determine instance name due to unparsable tokens
    * WARN: Check has either failed or produced a warning. See our wip spec for further info https://gist.github.com/m4rc1e/8f4c4498519e8a36cd54e16a004275cb

    Result: WARN

```

**Comment by kosbarts** [comment]
Warn is the expected behaviour now for such variable families, correct? So shall I close it?

**Comment by felipesanches** [comment]
@m4rc1e: 

```
    * WARN: Instance "Flair Thin": contains the following unparsable tokens "['Flair']"
```

I think it should instead say:
```
    * WARN: Instance "Flair Thin": contains the following unparsable tokens: "Flair"
```

I will create a new issue on the FontBakery tracker to implement this slight aestethical improvement to the output.

**Comment by felipesanches** [comment]
My understanding is that Loud and Flair should be part of the family name, and that this means the family should be split into two families: "Commissioner Flair" and "Commissioner Loud". Is that right, @davelab6 & @m4rc1e?

**Comment by kosbarts** [comment]
@felipesanches are we talking about the Statics? Because the Variable is one file. Commissioner.

**Comment by felipesanches** [comment]
yes, the instances. But I am not sure about it. I'd like to hear what @davelab6 and/or @m4rc1e think about it.

**Comment by kosbarts** [comment]
@felipesanches the static instances are already broken into 3 families: Commissioner, Commissioner Flair, and Commissioner Loud. 
I don't see the point of splitting the Variable font into different sub families.

**Comment by felipesanches** [comment]
I think you're right. No need to split the varfont. My dout is regarding the statics (named instances)

**Comment by davelab6** [comment]
I think this issue can be closed; its not a problem with the font, but with the check

**Comment by felipesanches** [comment]
thanks, Dave!
