### ISSUE TITLE
💔 ERROR: Glyphs are similiar to Google Fonts version?

### ISSUE THREAD

**Issue by kosbarts** [kosbarts/Commissioner#27]
ERROR: Glyphs are similiar to Google Fonts version?
com.google.fonts/check/production_glyphs_similarity

💔 ERROR The condition FontBakeryCondition:api_gfonts_ttFont had an error: FailedConditionError: The condition FontBakeryCondition:remote_styles had an error: FailedConditionError: The condition FontBakeryCondition:familyname_with_spaces had an error: TypeError: expected string or bytes-like object

**Comment by kosbarts** [comment]
@felipesanches Same as Issue#26. Unreleased project. Why does it report an Error?

**Comment by felipesanches** [comment]
Please update to the latest FB version and report a bug if you still get an ERROR.
