### ISSUE TITLE
💔 ERROR: Check if the vertical metrics of a family are similar to the same family hosted on Google Fonts.

### ISSUE THREAD

**Issue by kosbarts** [kosbarts/Commissioner#28]
--- Rationale ---

If the family already exists on Google Fonts, we need to ensure that the
checked family's vertical metrics are similar. This check will test the
following schema which was outlined in Fontbakery issue #1162 [1]:

- The family should visually have the same vertical metrics as the
  Regular style hosted on Google Fonts.
- If the family on Google Fonts has differing hhea and typo metrics,
  the family being checked should use the typo metrics for both the
  hhea and typo entries.
- If the family on Google Fonts has use typo metrics not enabled and the
  family being checked has it enabled, the hhea and typo metrics
  should use the family on Google Fonts winAscent and winDescent values.
- If the upms differ, the values must be scaled so the visual appearance
  is the same.

[1] https://github.com/googlefonts/fontbakery/issues/1162

💔 ERROR The condition FontBakeryCondition:remote_styles had an error: FailedConditionError: The condition FontBakeryCondition:familyname_with_spaces had an error: TypeError: expected string or bytes-like object

**Comment by kosbarts** [comment]
@felipesanches Same as Issue#26. Unreleased project. Why does it report an Error?

**Comment by felipesanches** [comment]
A FAIL is a problem with the font, while an ERROR is a problem with the tool (FontBakery) itself. Please update FB to the latest version and report a bug if the problem persists.

**Comment by kosbarts** [comment]
@felipesanches sweet mate! All Errors are gone after the update. Thanks.
