### ISSUE TITLE
Fontbakery Subfamily Check and correct STAT table conflict.

### ISSUE THREAD

**Issue by kosbarts** [kosbarts/Commissioner#33]
Commissioner is designed with two master for the `wght` axis, a Thin and a Black, which correspond to the equivalent Thin and Black weights in the instances (100 and 900). The font origin is the Thin master.

I have compared two different approaches in building the STAT and name tables and here are the results.

### **Case A)**

**Variable font behaviour**
- Font name shows as Commissioner Thin.
<img width="273" alt="Screenshot 2020-04-28 at 12 38 01" src="https://user-images.githubusercontent.com/5067985/80472256-2685a000-894d-11ea-9bd1-2b636750da37.png">

- Thin is flagged as 'normal' value and ElidedFallbackName.
- Italic name in STAT table appears _wrongly_ when `wght`=100 (Thin) and `slnt`=-12. 
<img width="274" alt="Screenshot 2020-04-28 at 12 34 07" src="https://user-images.githubusercontent.com/5067985/80471799-96dff180-894c-11ea-9618-0cb5c3f9c05f.png">

- `wght`=400 (Regular) and `slnt`=-12 produces Regular Italic
- All other name combinations are correct. 

**Relevant STAT values**
```
    <AxisValue index="0" Format="2">
      <AxisIndex value="0"/>
      <Flags value="2"/>
      <ValueNameID value="260"/> <!-- Thin -->
      <NominalValue value="100.0"/>
      <RangeMinValue value="100.0"/>
      <RangeMaxValue value="150.0"/>
    </AxisValue>
	
    <AxisValue index="1" Format="2">
      <AxisIndex value="0"/>
      <Flags value="0"/>
      <!-- ExtraLight -->
      <ValueNameID value="261"/> <!-- ExtraLight -->
      <NominalValue value="200.0"/>
      <RangeMinValue value="150.0"/>
      <RangeMaxValue value="250.0"/>
    </AxisValue>
	
    <AxisValue index="2" Format="2">
      <AxisIndex value="0"/>
      <Flags value="0"/>
      <ValueNameID value="262"/> <!-- Light -->
      <NominalValue value="300.0"/>
      <RangeMinValue value="250.0"/>
      <RangeMaxValue value="350.0"/>
    </AxisValue>
	
    <AxisValue index="3" Format="2">
      <AxisIndex value="0"/>
      <Flags value="0"/>
      <ValueNameID value="263"/> <!-- Regular -->
      <NominalValue value="400.0"/>
      <RangeMinValue value="350.0"/>
      <RangeMaxValue value="450.0"/>
    </AxisValue>
	
    <AxisValue index="4" Format="2">
      <AxisIndex value="0"/>
      <Flags value="0"/>
      <ValueNameID value="264"/> <!-- Medium -->
      <NominalValue value="500.0"/>
      <RangeMinValue value="450.0"/>
      <RangeMaxValue value="550.0"/>
    </AxisValue>
	
    <AxisValue index="5" Format="2">
      <AxisIndex value="0"/>
      <Flags value="0"/>
      <ValueNameID value="265"/> <!-- SemiBold -->
      <NominalValue value="600.0"/>
      <RangeMinValue value="550.0"/>
      <RangeMaxValue value="650.0"/>
    </AxisValue>
	
    <AxisValue index="6" Format="2">
      <AxisIndex value="0"/>
      <Flags value="0"/>
      <ValueNameID value="266"/> <!-- Bold -->
      <NominalValue value="700.0"/>
      <RangeMinValue value="650.0"/>
      <RangeMaxValue value="750.0"/>
    </AxisValue>
	
    <AxisValue index="7" Format="2">
      <AxisIndex value="0"/>
      <Flags value="0"/>
      <ValueNameID value="267"/> <!-- ExtraBold -->
      <NominalValue value="800.0"/>
      <RangeMinValue value="750.0"/>
      <RangeMaxValue value="850.0"/>
    </AxisValue>
	
    <AxisValue index="8" Format="2">
      <AxisIndex value="0"/>
      <Flags value="0"/>
      <ValueNameID value="268"/> <!-- Black -->
      <NominalValue value="900.0"/>
      <RangeMinValue value="850.0"/>
      <RangeMaxValue value="900.0"/>
    </AxisValue>
	
	<!-- ===== STYLE LINKING REGULAR-BOLD ===== -->
    <AxisValue index="9" Format="3">
      <AxisIndex value="0"/>
      <Flags value="0"/>
      <ValueNameID value="263"/> <!-- Regular -->
      <Value value="400"/>
	  <LinkedValue value="700"/>
    </AxisValue>

    <!-- ===== SLANT ===== -->
    <AxisValue index="10" Format="3">
      <AxisIndex value="1"/>
	  <!-- ElidedFallbackNameID value (Upright) -->
      <Flags value="2"/>
      <ValueNameID value="314"/> <!-- Upright -->
      <Value value="0"/>
	  <LinkedValue value="-12"/>
    </AxisValue>
	
    <AxisValue index="11" Format="1">
	  <AxisIndex value="1"/>
      <Flags value="0"/>
	  <ValueNameID value="315"/> <!-- Italic -->
      <Value value="-12"/>
    </AxisValue>
```

and 

`<ElidedFallbackNameID value="2"/> <!-- Thin -->`

**Name records**

```
<namerecord nameID="1" platformID="1" platEncID="0" langID="0x0" unicode="True">
      Commissioner
<namerecord nameID="2" platformID="1" platEncID="0" langID="0x0" unicode="True">
      Thin
<namerecord nameID="1" platformID="3" platEncID="1" langID="0x409">
      Commissioner   
<namerecord nameID="2" platformID="3" platEncID="1" langID="0x409">
      Thin
```

**Font Bakery reports**

```
🍞 PASS: Check name table: FONT_SUBFAMILY_NAME entries.

🍞 PASS: Check name table: TYPOGRAPHIC_SUBFAMILY_NAME entries.
```

### **Case B)** 

**Variable font behaviour**
- Font name shows as Commissioner.
<img width="270" alt="Screenshot 2020-04-28 at 12 39 43" src="https://user-images.githubusercontent.com/5067985/80472432-63519700-894d-11ea-881f-a11df6c7f75d.png">

- Regular is flagged as 'normal' value and ElidedFallbackName.
- Italic name in STAT table appears correctly when `wght`=400 (Regular) and `slnt`=-12. <img width="278" alt="Screenshot 2020-04-28 at 12 02 25" src="https://user-images.githubusercontent.com/5067985/80468975-95acc580-8948-11ea-97c0-18ab1f8ad67a.png">

- All other name combinations are correct. 

**Relevant STAT values**
```
    <AxisValue index="0" Format="2">
      <AxisIndex value="0"/>
      <Flags value="0"/>
      <ValueNameID value="260"/> <!-- Thin -->
      <NominalValue value="100.0"/>
      <RangeMinValue value="100.0"/>
      <RangeMaxValue value="150.0"/>
    </AxisValue>
	
    <AxisValue index="1" Format="2">
      <AxisIndex value="0"/>
      <Flags value="0"/>
      <!-- ExtraLight -->
      <ValueNameID value="261"/> <!-- ExtraLight -->
      <NominalValue value="200.0"/>
      <RangeMinValue value="150.0"/>
      <RangeMaxValue value="250.0"/>
    </AxisValue>
	
    <AxisValue index="2" Format="2">
      <AxisIndex value="0"/>
      <Flags value="0"/>
      <ValueNameID value="262"/> <!-- Light -->
      <NominalValue value="300.0"/>
      <RangeMinValue value="250.0"/>
      <RangeMaxValue value="350.0"/>
    </AxisValue>
	
    <AxisValue index="3" Format="2">
      <AxisIndex value="0"/>
      <Flags value="2"/>
      <ValueNameID value="263"/> <!-- Regular -->
      <NominalValue value="400.0"/>
      <RangeMinValue value="350.0"/>
      <RangeMaxValue value="450.0"/>
    </AxisValue>
	
    <AxisValue index="4" Format="2">
      <AxisIndex value="0"/>
      <Flags value="0"/>
      <ValueNameID value="264"/> <!-- Medium -->
      <NominalValue value="500.0"/>
      <RangeMinValue value="450.0"/>
      <RangeMaxValue value="550.0"/>
    </AxisValue>
	
    <AxisValue index="5" Format="2">
      <AxisIndex value="0"/>
      <Flags value="0"/>
      <ValueNameID value="265"/> <!-- SemiBold -->
      <NominalValue value="600.0"/>
      <RangeMinValue value="550.0"/>
      <RangeMaxValue value="650.0"/>
    </AxisValue>
	
    <AxisValue index="6" Format="2">
      <AxisIndex value="0"/>
      <Flags value="0"/>
      <ValueNameID value="266"/> <!-- Bold -->
      <NominalValue value="700.0"/>
      <RangeMinValue value="650.0"/>
      <RangeMaxValue value="750.0"/>
    </AxisValue>
	
    <AxisValue index="7" Format="2">
      <AxisIndex value="0"/>
      <Flags value="0"/>
      <ValueNameID value="267"/> <!-- ExtraBold -->
      <NominalValue value="800.0"/>
      <RangeMinValue value="750.0"/>
      <RangeMaxValue value="850.0"/>
    </AxisValue>
	
    <AxisValue index="8" Format="2">
      <AxisIndex value="0"/>
      <Flags value="0"/>
      <ValueNameID value="268"/> <!-- Black -->
      <NominalValue value="900.0"/>
      <RangeMinValue value="850.0"/>
      <RangeMaxValue value="900.0"/>
    </AxisValue>

    <AxisValue index="9" Format="3">
      <AxisIndex value="0"/>
      <Flags value="0"/>
      <ValueNameID value="263"/> <!-- Regular -->
      <Value value="400"/>
	  <LinkedValue value="700"/>
    </AxisValue>

    <AxisValue index="10" Format="3">
      <AxisIndex value="1"/>
      <Flags value="2"/>
      <ValueNameID value="314"/> <!-- Upright -->
      <Value value="0"/>
	  <LinkedValue value="-12"/>
    </AxisValue>
	
    <AxisValue index="11" Format="1">
	  <AxisIndex value="1"/>
      <Flags value="0"/>
	  <ValueNameID value="315"/> <!-- Italic -->
      <Value value="-12"/>
    </AxisValue>
```

and 

`<ElidedFallbackNameID value="2"/> <!-- Regular -->`

**Name records**

```
<namerecord nameID="1" platformID="1" platEncID="0" langID="0x0" unicode="True">
      Commissioner
<namerecord nameID="2" platformID="1" platEncID="0" langID="0x0" unicode="True">
      Regular
<namerecord nameID="1" platformID="3" platEncID="1" langID="0x409">
      Commissioner   
<namerecord nameID="2" platformID="3" platEncID="1" langID="0x409">
      Regular
```

**Font Bakery reports**

```
<summary>🔥 <b>FAIL:</b> Check name table: FONT_SUBFAMILY_NAME entries.</summary>
* 🔥 **FAIL** SUBFAMILY_NAME for Mac "Regular" must be "Thin" [code: bad-familyname]


<summary>🔥 <b>FAIL:</b> Check name table: TYPOGRAPHIC_SUBFAMILY_NAME entries.</summary>
* 🔥 **FAIL** TYPOGRAPHIC_SUBFAMILY_NAME for Win "Regular" is incorrect. It must be "Thin". [code: bad-typo-win]
```

@thundernixon would you have any feedback on this? I saw that Recursive has a good STAT structure and reports the same FAILs in FontBakery

@davelab6 as far as I can understand Fontbakery expects a value that will correspond to what the user might get if they load the variable file in a non-variable environment, so the subfamily will accurately display what the user sees (i.e. Commissioner Thin, being the default stored outlines).

**Comment by arrowtype** [comment]
**STAT**

@kosbarts Ben Kiel gets the credit for making the STAT table in Recursive. You can look at his scripts in the `mastering` folder of the project.

I recommend trying statmake for this, if it will work with your family. I have recently found it useful to use it with python dictionaries, rather than trying to write it directly or apply it directly via ttFont or the like. Check out:

- https://github.com/thundernixon/Libre-Caslon/blob/184d1dfeeaeca806521f8843b01148f488ebbb06/sources/scripts/set-stat-table.py

- https://github.com/thundernixon/Encode-Sans/blob/fe44e5ca241ad7acc13fd225019855a87601da3e/sources/scripts/helpers/add-stat-table.py

**Name records**

- name 1 should be `Commissioner Thin`, if that is the default instance.
- name 1 should have the family name + the stylename, if the default instance isn't RIBBI (reg, ital, bold, bold ital)
- name 2 should be ’Regular’ unless it's italic, bold, or bold italic.

See https://github.com/googlefonts/gf-docs/tree/master/Spec#supported-styles for suggested naming (this is for statics, but is the same based on the default style of your VF, as far as I know).

It can be useful to search in the fontbakery repo to find how different terms are defined. For instance, you can see in [constants.py](https://github.com/googlefonts/fontbakery/blob/fc6ed79e77801ad84998bfc7d310820477713af8/Lib/fontbakery/constants.py#L162) that `FONT_SUBFAMILY_NAME` is name 2, while `TYPOGRAPHIC_SUBFAMILY_NAME` is name 17. 

So yes, it appears that the first `FAIL` is incorrect, _but_ “Thin” should be in name 1. The second `FAIL` is true, as name 17 is more for the style menu of apps like in Sketch or InDesign, and therefore should have the style name.

**Comment by arialcrime** [comment]
I agree with @kosbarts. 

While I know that this is what it says in Fontbakery and the Google Font Spec, I don’t think that it is a good idea to name the entire variable font by the default master, specifically when there is more than a width and weight axis, and the default is not “the regular”.

In [Fraunces](https://github.com/undercasetype/Fraunces/tree/alphabet) (which works similarly to the Caslon you linked to in terms of file structure; 2 files for the family) the proposed naming would be `Fraunces 144pt S100 Black` (the name of the default master). I am aware that this is how ufo2ft handles things at the moment, but looking beyond the usage of the font as a webfont, I would argue that the name should be `Fraunces`. But maybe I am missing something obvious here.

**Comment by arrowtype** [comment]
Name 16 would be `Fraunces`, and that is what will be used in font menus for platforms/apps that support variable fonts.

As far as I understand, Name 1 is used by legacy software which can’t parse the new tables (fvar, gvar, etc), such as old MS Word or Ubuntu Linux as recently as early 2018 (see first comment [here](https://meyerweb.com/eric/thoughts/2018/09/05/variable-font-support/). What name should users see as the font name if they can *only* see the default style of the variable font?

At least, this is the logic for the GF spec’s recommendations. It’s definitely not intuitive, but it’s trying to support legacy software as well as realistically possible. If you can find something that proves that that approach isn’t the best, then it would be good to file an issue on gf-docs or google/fonts.

**Comment by davelab6** [comment]
FontBakery and the GF Spec should be considered WIP at this point, not a firm policy, right @m4rc1e?

**Comment by m4rc1e** [comment]
Dave, Correct.

Stephen, 

> Name 16 would be Fraunces, and that is what will be used in font menus for platforms/apps that support variable fonts.

Correct.

> As far as I understand, Name 1 is used by legacy software which can’t parse the new tables (fvar, gvar, etc), such as old MS Word or Ubuntu Linux as recently as early 2018 (see first comment here. What name should users see as the font name if they can only see the default style of the variable font?

Correct, minus the VF table parts. The MS Spec states,

> While some platforms or applications do not have this constraint, many existing applications that use this pair of names assume that a Font Family name is shared by at most four fonts that form a font style-linking group: regular, italic (or oblique), bold, and bold italic (or bold oblique). To be compatible with the broadest range of platforms and applications, it is strongly recommended that fonts limit use of Font Family name in this manner.

> For extended typographic families that includes fonts other than the four basic styles (regular, italic, bold, bold italic), it is strongly recommended that name IDs 16 and 17 be used in fonts to create an extended, typographic grouping. (See examples provided below.)

https://docs.microsoft.com/en-us/typography/opentype/spec/name

**Comment by arrowtype** [comment]
Thanks for the helpful additions, Dave and Marc!

Right, I didn’t say that very clearly – name 1 isn’t ONLY used by legacy software, as my comment may have suggested. It is used to represent single (static) fonts in a way that requires a special consideration to RIBBI vs other styles. 

And, if a variable font is on a legacy platform, it gets treated as a static font (which has the style of the default instance). So, for that case, name 1 & 2 should be treated as the default instance would be in a static font.

**Comment by kosbarts** [comment]
@arrowtype @m4rc1e 

That is very helpful from both of you. Thank you very much!
