### ISSUE TITLE
Spacing bug

### ISSUE THREAD

**Issue by RosaWagner** [kosbarts/Commissioner#35]
So after few tests, the bug described in https://github.com/google/fonts/pull/2561 is indeed a component issue.
To avoid thatt I would suggest to:

- [ ] decompose all the non-accented base letters (i,  j, Q, Alpha, A-cy etc.)
- [x] avoid nested components
- [x] have the same number of kerning pairs in all masters (use mekkablue script: zero kerner)
- [x] maybe re-interpolate metrics of brace layers

**Comment by kosbarts** [comment]
Rosa, are you sure about decomposing all base letters? That would require a script to be written to run on the source file (same principle as Decompose Transformed Components) and then save as a -production glyphs file to be used by the builds. 

I wouldn't want anyone who tries to work on the source file to have to copy 16 masters (or duplicate/delete/rename) from A to A-cy, etc, etc. That would be totally mental.

**Comment by kosbarts** [comment]
@RosaWagner what tool do you use to test across browsers / operating systems?

**Comment by RosaWagner** [comment]
[Samsa](https://www.axis-praxis.org/samsa/) mostly

**Comment by kosbarts** [comment]
But you run the tests on different computers/systems?

**Comment by RosaWagner** [comment]
Only if there is something special to check. Otherwise I QA with diffbrowser (gftool qa), but you need credentials for that. Generate the fonts and I will run diffbrowser on it.

**Comment by kosbarts** [comment]
I have done the ticked changes but I would like to avoid decomposing base components for now. Let's test and If the problem persists then we can try to decompose components.

**Comment by RosaWagner** [comment]
The problem is the component, I already tested it. You can't add a string of base letters to decompose to the "decompose-transformed-components" script ?

**Comment by kosbarts** [comment]
I could. What is the problem with the component though? If you could be more specific perhaps we could find a workaround. Is Commissioner the only font that you have had such an issue with?

**Comment by RosaWagner** [comment]
It is a bug of Safari (maybe fixed on the last OS), it does that with composites; so we try to have, at least, the base letters decomposed.

**Comment by kosbarts** [comment]
So it is common practice for all fonts that go live on Google Fonts?

**Comment by RosaWagner** [comment]
It is common practice for all fonts that are being produced I think :) And Google doesn't have the most radical position concerning components XD When you export from Glyphs, there is a custom parameter to decompose *all* composites, just for the variable font, to prevent this issue.

**Comment by kosbarts** [comment]
I think it is easier to decompose all composites than to cherry-pick the base letters.

**Comment by RosaWagner** [comment]
Then the font file is bigger

**Comment by kosbarts** [comment]
Yes. But it won't drive me mad! 😃

So in your suggestion: decompose all the non-accented base letters (i, j, Q, Alpha, A-cy etc.), why is i and j in your list? Are you referring to i-cy and je-cy.

**Comment by RosaWagner** [comment]
I put /i and /j because they are not considered as accented letters in western latin languages, and they are ones tested by our QA tools.

**Comment by kosbarts** [comment]
I thought it had to do with glyphs being made of components and not about language semantics. Sorry for making all these painful questions!

**Comment by RosaWagner** [comment]
Haha ok. Look, the problem concerns all glyphs made of components, but the tool where the spacing issue appears is only testing a minimal amount of glyphs. So it's always the same, the basic idea is to make western people happy by decomposing /i and /j. I suggest to decompose all base letters, to make more people happy. If you decompose everything, even more people will be happy, but probably not the engineers.

**Comment by RosaWagner** [comment]
Or I just fill an issue to make them test the browser previews on a more recent OS where Safari doesn't bug.

**Comment by kosbarts** [comment]
OK Rosa. So far I have done the following:
- Added exact same number of kerning pairs in all masters
- Decomposed and got rid of all transformed components 
- Re-interpolated metrics of brace layers and removed key-references from both sides.
- Changed Readme.md

I have pushed the latest file. Would you mind running a test on this one while I try and see how to workaround the decomposition of base letters?

**Comment by RosaWagner** [comment]
Ok, I send you the test tomorrow morning.

**Comment by RosaWagner** [comment]
The /i is still dancing
![Capture d’écran 2020-09-09 à 12 31 40](https://user-images.githubusercontent.com/12222436/92587848-7def3180-f298-11ea-9d45-043f561a7c06.png)

**Comment by kosbarts** [comment]
I see. So what is the verdict? Do we satisfy all potential users by decomposing everything or do we just satisfy Westerners by decomposing i, j...? What happens with í or ï?

**Comment by RosaWagner** [comment]
I don't know, the bug only concerns safari on older version of Mac OS, it seems radical to decompose everything. Just decomposing /i would satisfy the robot actually.

**Comment by kosbarts** [comment]
I don't get why it is happening with Commissioner. I just downloaded Recursive variable from https://github.com/google/fonts/tree/9d79f50a74d375e56e253bfca96ddc1d2aba6b67/ofl/recursive and the i is made of composites. 🤦
The vf is unhinted, so is it the outline of the idotless? The outline of the dotaccent? What is it that causes this.

**Comment by RosaWagner** [comment]
Recursive is a monospace, so the spacing is not changing with the weight axis. Although I note the same issue with the "monospace" slider that changes the width. OK wait, I gonna ask Dave again with these new arguments.

**Comment by RosaWagner** [comment]
Can you test your font in Safari Catalina ? Like, drop it in [wakamai fondue](https://wakamaifondue.com) and see if the spacing jiggles when you move the weight slider. I would like the confirmation that there is no HVAR issue in more recent OS.

**Comment by kosbarts** [comment]
Sorry, I am on Mojave still. Let me see if I can access someone with Catalina.

**Comment by kosbarts** [comment]
<img width="1083" alt="Screenshot 2020-09-09 at 15 13 58" src="https://user-images.githubusercontent.com/5067985/92597264-cf56eb00-f2af-11ea-8676-49408152c105.png">
<img width="571" alt="Screenshot 2020-09-09 at 15 14 19" src="https://user-images.githubusercontent.com/5067985/92597274-d2ea7200-f2af-11ea-906b-fb219c2b7f9f.png">

**Comment by RosaWagner** [comment]
Yes, but it depends on the location… is the spacing correct all along ? Or does it move weirdly ?

**Comment by kosbarts** [comment]
No jiggling. Spacing is correct all along.

**Comment by RosaWagner** [comment]
Ok we got the go from Dave, let's send the new version without decomposing everything

**Comment by kosbarts** [comment]
Excellent. Do you need anything else from me?

**Comment by RosaWagner** [comment]
all good thanks

**Comment by RosaWagner** [comment]
Actually, can you export the statics with the changes you made ?

**Comment by kosbarts** [comment]
Yes. Will do it promptly and push.

**Comment by RosaWagner** [comment]
Send me a little bio of you for the designer section

**Comment by kosbarts** [comment]
Ah! Now you are making it hard for me! Lol. I will send it soon.

**Comment by kosbarts** [comment]
Where can I send the bio?

**Comment by RosaWagner** [comment]
send me an email

**Comment by kosbarts** [comment]
sent

**Comment by kosbarts** [comment]
And pushed all new otfs + ttfs.

**Comment by RosaWagner** [comment]
https://github.com/google/fonts/pull/2675
