### ISSUE TITLE
Which source file ?

### ISSUE THREAD

**Issue by RosaWagner** [kosbarts/Commissioner#36]
Following Dave's email:

- Would it be possible to reduce the number of source file to one ?
- Same for the build script, maybe one for the vf, one for the statics and one for all. But 2 for the vf is a bit confusing.

**Comment by kosbarts** [comment]
Decomposing transformed components and possibly decomposing base letters and keeping all these on the source file will make it unusable in the future. We need at least one source file with clean outlines and components in place and one file that we can use for the builds that has any decomposed comps. 

The reason I made 2 different vf builds is that I didn't only have Google production in mind but wanted to offer any person who downloads the repo more control according to their preference. There may be other ways to do the production but they are outside my scope to be honest.

**Comment by RosaWagner** [comment]
As you wish, a subfolder would be in that case pretty handy :)

**Comment by kosbarts** [comment]
OK. I have changed the build strategy. One source file. One set of builds for each case (static, vf, all).
