### ISSUE TITLE
Fs selection bit 7

### ISSUE THREAD

**Issue by RosaWagner** [kosbarts/Commissioner#37]
Use_Typo_Metrics has to be enable in the font custom parameter

**Comment by kosbarts** [comment]
The values are identical so I thought there is no reason to have it activated. Is there?

**Comment by RosaWagner** [comment]
We need it to be activated for several reasons:
1. Your WIN metrics and your TYPO metrics are actually different, and we need Windows app to read the TYPO metrics 
2. In case you add another script in the future, we will be able to change the WIN metrics (to avoid clipping) without having regression of the linespacing

**Comment by kosbarts** [comment]
You are totally right! I don't know what I saw and thought they are the same. 🤦
