### ISSUE TITLE
Variable font for Google and Instances

### ISSUE THREAD

**Issue by kosbarts** [kosbarts/Commissioner#38]
@davelab6 the way @yanone has altered the builds, drops all instances that are not supported by GF at the moment. However, I think that this repo should produce a variable font as intended by the designer, with all instances included. We should perhaps include one additional build-vf that just gets rid of the Google undesired instances and creates a GF friendly VF font and one other build-vf that builds a variable font as it was designed. 

In any case, I think people that clone or download the font from the repo should get it as is.

Thoughts?

**Comment by RosaWagner** [comment]
Maybe release just the actual GF version without the unsupported fvar instances, and when it is available on GF, then push an increased version of the variable with all the instances. With a bit of luck it will be the next update on GF. (With the actual GF version in a "old" folder where we can still find it.)

**Comment by kosbarts** [comment]
Sure. I can do that.
