### ISSUE TITLE
wrong uppercase glyphs?

### ISSUE THREAD

**Issue by ousia** [kosbarts/Commissioner#46]
@kosbarts,

many thanks for releasing your Commissioner font under a free license.

Using your variable font with weight 700, I get the following:

![commission-1-fs8](https://user-images.githubusercontent.com/203767/197323709-dafb94d2-b9ec-4865-9a12-9392b6c07ce8.png)

Comparing it to the static sizes, I’m afraid this might be wrong (uppercase e, f, ε, φ, ξ).

Am I missing something or have I hit a bug?

Many thanks for your help.

**Comment by kenmcd** [comment]
What operating system?
What application are you using?
What version of the variable font are you using?
Where did you get the font, from Google Fonts or from here in the repository?

I do not see anything wrong with those characters so I am guessing it is an application issue.

**Comment by ousia** [comment]
@kenmcd, many thanks for your reply.

Excuse my poor reporting.

OS is Linux (Fedora 35). The program is ConTeXt.

The variable version I’m using is from this repository (https://github.com/kosbarts/Commissioner/releases/tag/1.000) and it is named `Commissioner_VF_1.001.ttf` (SHA512 `d801471944157b84a0743e81d715915ef049ef45a73ea59913d60aa20427dc1a771c51d8dd2e1b9dcd932d4b9acec87676ce35eb1ead2f07475bcf948921fac1`).

I thought I hadn’t other program to test it, but Inkscape displays the glyphs perfectly fine.

![a-commissioner](https://user-images.githubusercontent.com/203767/197393658-2a680a8b-84a0-405b-ac14-0c779c80897c.svg)

So it seems that ConTeXt is misreading the font.

Closing the issue myself and many thanks for your help.
