### ISSUE TITLE
Missing capital Kai symbol

### ISSUE THREAD

**Issue by cssobral2013** [kosbarts/Commissioner#51]

**Comment by kosbarts** [comment]
@cssobral2013 why do you need it? There is a lowercase one and it can work with uppercase letters fine.

**Comment by cssobral2013** [comment]
@kosbarts - It is strongly recommended that every Unicode-mapped lowercase glyph have an uppercase counterpart if it has one.

**Comment by cssobral2013** [comment]
@kosbarts - A suggestion: why not copy current Kai symbol in uppercase, then adapt it?

**Comment by kosbarts** [comment]
@cssobral2013 but do you actually need the glyph? Are you going to use it in any context that they lowercase doesn't fit it?
